package com.lee.mymvvmsample.common.utils

object Constants {
    val FORE_GROUND_ID = 11459
    val CHANNEL_ID = "channelID_19152"
    val CHANNEL_NAME = "DustAppChannelName"
    val MYAUTOSERVICE_CHANNEL_ID = "MYAUTOSERVICE_CHANNEL_ID"
    val MYAUTOSERVICE_FORE_GROUND_ID = 20483

    val INTRO_BROADCAST_MESSAGE = "com.lee.dustapp.BR_MESSAGE_INTRO"
    val NOTIFICATION_BROADCAST_MESSAGE = "com.lee.dustapp.BR_MESSAGE_NOTIFICATION"
    val JOBSCHEDULER_BROADCAST_MESSAGE = "com.lee.dustapp.BR_MESSAGE_JOBSCHEDULER"
    val SET_NOTIFICATION_BR_MESSAGE = "com.lee.dustapp.BR_SET_NOTIFICATION_MESSAGE"

    val JOB_SCHEDULE_ID = 24569
}